
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - staight.k8s.io
  resources:
  - alpines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - staight.k8s.io
  resources:
  - alpines/status
  verbs:
  - get
  - patch
  - update
